version: '3.9'

##https://www.ritolab.com/entry/232#aj_3 参考

services:
  minio:
    image: 'minio/minio'
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadminuser
      MINIO_ROOT_PASSWORD: minioadminpassword
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./docker/minio/data:/export
    ports:
      - '9000:9000'
      - '9001:9001'
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio