spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug

s3:
  #minioのコンソールログインと同じ
  credential:
    accessKey: minioadminuser
    secretKey: minioadminpassword
  region: ap-northeast-1
  endPoint: http://localhost:9000
  bucketName: localbucket
  connectionTimeout: 10000
  readTimeout: 10000